NF: Add database functionality
SincereSingularities/SincereSingularities pull request #6
Opened 2024-07-23 13:42 UTC by WassCodeur

### Add database functionality

#### Description
This PR adds database functionality to manage data and its menus. The main changes are as follows:

- Added a `restaurant_menus` collection to store information about restaurants and their menus.
- Added verification to avoid duplicates before inserting documents.
- Use of the `pymongo` module to interact with MongoDB.

#### Tests carried out
- Verification of document insertion without duplication.
- Tested basic CRUD operations on the `restaurant_menus` collection.

#### How to test
1. Install dependencies with `pip install -r requirements.txt`.
2. Configure  [MongoDB](https://www.prisma.io/dataguide/mongodb/setting-up-a-local-mongodb-database) and launch the server.
3. Create the `.env` file, copy the contents of `.env.example` and update the database variables with the values from your mongodb database: 
4. Run the `data/db.py` script to test functionality.

#### Additional comments
We welcome any suggestions or improvements!

2024-07-23 17:12 UTC, koviubi56 requested changes
1. Setup instructions for the db should be included in the README.
2. Better docstrings for classes and functions. (see [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html))
3. Follow PEP8 by using snake_case for function names.
4. Don't return strings as a result; raise an exception for errors.
5. Simplify if-statements:
  ```py
  # instead of this:
  if self.connected:
     # ...code...
  else:
     raise ...

  # do this:
  if not self.connected:
      raise ...
  # ...code...
  ```
6. `dict.get(x)` might return None. Either set a default or use `dict[x]`
7. Try to use general type hints for parameters:
  ```py
  # x doesn't need to be a list, it just needs to be iterable
  def f(x: Iterable[str]) -> None:
      for something in x:
          g(something)
  ```
8. Consider raising an exception instead of returning None.
9. I'm not sure if we're gonna have tests.

2024-07-23 21:33 UTC, WassCodeur commented
Hi @koviubi56 !

Thank you for your feedback

2024-07-24 07:34 UTC, koviubi56 approved these changes
It LGTM, but I'm wondering: is it worth it to use MongoDB? You have to install it, set it up; while there is [`sqlite3`](https://docs.python.org/3/library/sqlite3.html) in stdlib that doesn't need to be set up. So is there a specific reason you chose MongoDB?

2024-07-24 13:45 UTC, WassCodeur commented
Hello @koviubi56,

thanks for your comment. In fact, I used mongoDB because of its ability to support several types of data (dynamic schema and rich queries) for one entity, in addition to its scalability and high read/write performance. By the way, you can also use the online version of mongoDB, so there's no need to install the server locally.

2024-07-24 15:22 UTC, Vinyzu commented
This is marked as a WIP (Work in Progress).
The current goal of the database is a MongoDB which we can push/pull the savestates to.
We might extend the databases use case if we feel like it fits us well.

2024-07-25 18:46 UTC, koviubi56 requested changes
Thank you. If you could fix my recommendations, that'd be great. Also, could you implement what I temporarily implemented in `points.py` (between the two comments)?

2024-07-25 18:46 UTC, koviubi56 commented on requirements.txt
> -numpy<2
Why did these get removed?

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/db.py
> +            self.db[collection].delete_one(data)
Maybe raise an exception if it didn't exist in the first place? (also in `delete_many`)

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/db.py
> +    def show_all(self, collection: str) -> Iterable[dict[str, Any]]:
You can specify that the return value is a list.

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/db.py
> +        return {}
Raise instead.

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/db.py
> +        if element:
Raise exception if it doesn't exist in the first place. (also in update_many)

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/restaurants.json
>  [
Add points to the restaurants. The first one (index 0) should need 0 points, and the following ones should have more and more (see Pizzaria and Sushi Restaurant for example).

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/savestates.py
> +    def add_user_state(self, data: dict[str, Any]) -> None:
Maybe you could make this a TypedDict

2024-07-25 18:46 UTC, koviubi56 commented on src/sincere_singularities/data/states.json
> +[
Thanks, but I don't think we need example states.

2024-07-27 12:22 UTC, koviubi56 commented on src/sincere_singularities/data/restaurants.json
>  [
Actually, we already worked on this, so this addition isn't necessary.

2024-07-27 20:55 UTC, Vinyzu commented on README.md
> +2.  Test the bot in your discord server.
We will rework the ReadMe in the Presentation phase anyways.

2024-07-27 20:58 UTC, Vinyzu approved these changes
LGTM for now.
Will do some refractoring of the code tomorrow but its important that we get this code in the main branch to implement it tomorrow.

2024-07-28 08:35 UTC, koviubi56 approved these changes
LGTM

2024-07-28 09:50 UTC, merged