GUI based Orders are almost done.
SincereSingularities/SincereSingularities pull request #8
Opened 2024-07-23 16:05 UTC by Vinyzu

- Refractored some of the Code (Structure)
- Added Ordering Menu Selection Screen
- Added Order Check
- Implemented better Colors
- Added Quality of Life Buttons

2024-07-23 16:10 UTC, koviubi56 commented
Could you add `disallow_subclassing_any = false` to mypy's config (`pyproject.toml`) to make it happy?

2024-07-23 17:00 UTC, koviubi56 requested changes
If you can fix these then it's ok

2024-07-23 17:00 UTC, koviubi56 commented on src/sincere_singularities/modules/order.py
> +                    [f"- `{item_name}`: {menu_items.count(item_name)}" for item_name in list(set(menu_items))]
```suggestion
                    f"- `{item_name}`: {menu_items.count(item_name)}" for item_name in set(menu_items)
```

2024-07-23 17:00 UTC, koviubi56 commented on src/sincere_singularities/modules/order.py
> +    extra_information: str = ""
I'm not sure why it has `unsafe_hash` and why it has defaults.

2024-07-24 08:40 UTC, Vinyzu commented on src/sincere_singularities/modules/order.py
> +    extra_information: str = ""
Switched to `frozen=True` and removed defaults

2024-07-24 08:41 UTC, koviubi56 approved these changes
LGTM (after you fix the formatting)

2024-07-24 09:53 UTC, merged